config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :capabilities
  resources :topics
  resources :clinics

  get 'home' => 'clinics#home', as: :home
  get 'about' => 'clinics#about', as: :about
  get 'select_topic' => 'clinics#select_topic', as: :select_topic

  root 'clinics#home'

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  has_many :shifts, dependent: :destroy
  has_many :capabilities, dependent: :destroy
  has_many :topics, through: :capabilities
  
  accepts_nested_attributes_for :shifts
  accepts_nested_attributes_for :capabilities

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :lat, presence: true
  validates :lng, presence: true
  validates :country, presence: true

end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy]
  before_action :set_countries_and_time
  before_action :set_location
  before_filter :authenticate_admin!, only: [:edit, :update, :destroy]

  def csv
  end

  def home
  end

  def about
  end

  def select_topic
    @topics = Topic.all
  end

  # GET /clinics
  # GET /clinics.json
  def index
    @unverified_clinics = Clinic.where(verified: nil) + Clinic.where(verified: false)

    if params[:topic].present?
      @clinics = Topic.find_by(name: params[:topic]).available_clinics.select{|clinic| clinic.verified}
    else
      @clinics = Clinic.where(verified: true)
    end

    @clinics_sorted_by_distance = []

    if @lat_lng
      location = Geocoder.search(@lat_lng).first

      @clinics.each do |clinic|
        @clinics_sorted_by_distance << [clinic, Geocoder::Calculations.distance_between([@lat_lng.first, @lat_lng.last], [clinic.lat, clinic.lng], :units => :km).round(1)]
      end
      if location && location.city
        @current_location = [location.city, location.country]
      end
    else
      user_ip = request.remote_ip

      location = GeoIP.new('GeoLiteCity.dat').city(user_ip)

      if location
        @clinics.each do |clinic|
          @clinics_sorted_by_distance << [clinic, Geocoder::Calculations.distance_between([location.latitude, location.longitude], [clinic.lat, clinic.lng], :units => :km).round(2)]
        end
        @current_location = [location.city_name, location.country_name]
      else
        @clinics.each do |clinic|
          @clinics_sorted_by_distance << [clinic, 0]
        end
      end
    end

    @clinics_sorted_by_distance.sort_by!{|clinic| clinic.last}

    respond_to do |format|
      format.html

      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"ClinicFinder Clinics\".csv"
        headers['Content-Type'] ||= 'text/csv'

        render layout: false
      end

    end
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
    @shifts = @clinic.shifts.select{|s| s.open}
    @capabilities = @clinic.capabilities.select{|c| c.available}
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new

    @shifts = [
      @clinic.shifts.build(day: "mon"),
      @clinic.shifts.build(day: "tue"),
      @clinic.shifts.build(day: "wed"),
      @clinic.shifts.build(day: "thu"),
      @clinic.shifts.build(day: "fri"),
      @clinic.shifts.build(day: "sat"),
      @clinic.shifts.build(day: "sun")
    ]

    @capabilities = []

    Topic.all.each do |topic|
      @capabilities << @clinic.capabilities.build(topic_id: topic.id)
    end
  end

  # GET /clinics/1/edit
  def edit
    @shifts = @clinic.shifts.sort
    @capabilities = @clinic.capabilities

    Topic.all.each do |topic|
      unless @clinic.topics.include?(topic)
        @capabilities << @clinic.capabilities.build(topic_id: topic.id)
      end
    end

  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url, notice: 'Clinic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      if cookies[:lat_lng]
        @lat_lng = cookies[:lat_lng].split("|")
      end
    end

    def set_countries_and_time

      @times = ["0:00", "0:30", "1:00", "1:30", "2:00", "2:30", "3:00", "3:30", "4:00", "4:30", "5:00", "5:30", "6:00", "6:30", "7:00", "7:30", "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "24:00"]

      @countries = [
        [t(:AL, :scope => :countries), "AL"],
        [t(:AD, :scope => :countries), "AD"],
        [t(:AT, :scope => :countries), "AT"],
        [t(:BY, :scope => :countries), "BY"],
        [t(:BE, :scope => :countries), "BE"],
        [t(:BA, :scope => :countries), "BA"],
        [t(:BG, :scope => :countries), "BG"],
        [t(:HR, :scope => :countries), "HR"],
        [t(:CY, :scope => :countries), "CY"],
        [t(:CZ, :scope => :countries), "CZ"],
        [t(:DK, :scope => :countries), "DK"],
        [t(:EE, :scope => :countries), "EE"],
        [t(:FO, :scope => :countries), "FO"],
        [t(:FI, :scope => :countries), "FI"],
        [t(:FR, :scope => :countries), "FR"],
        [t(:GE, :scope => :countries), "GE"],
        [t(:DE, :scope => :countries), "DE"],
        [t(:GR, :scope => :countries), "GR"],
        [t(:HU, :scope => :countries), "HU"],
        [t(:IS, :scope => :countries), "IS"],
        [t(:IE, :scope => :countries), "IE"],
        [t(:IT, :scope => :countries), "IT"],
        [t(:LV, :scope => :countries), "LV"],
        [t(:LI, :scope => :countries), "LI"],
        [t(:LT, :scope => :countries), "LT"],
        [t(:LU, :scope => :countries), "LU"],
        [t(:RS, :scope => :countries), "RS"],
        [t(:MK, :scope => :countries), "MK"],
        [t(:MT, :scope => :countries), "MT"],
        [t(:MD, :scope => :countries), "MD"],
        [t(:ME, :scope => :countries), "ME"],
        [t(:NL, :scope => :countries), "NL"],
        [t(:NO, :scope => :countries), "NO"],
        [t(:PL, :scope => :countries), "PL"],
        [t(:PT, :scope => :countries), "PT"],
        [t(:RO, :scope => :countries), "RO"],
        [t(:RU, :scope => :countries), "RU"],
        [t(:RS, :scope => :countries), "RS"],
        [t(:SM, :scope => :countries), "SM"],
        [t(:RS, :scope => :countries), "RS"],
        [t(:SK, :scope => :countries), "SK"],
        [t(:SI, :scope => :countries), "SI"],
        [t(:ES, :scope => :countries), "ES"],
        [t(:SE, :scope => :countries), "SE"],
        [t(:CH, :scope => :countries), "CH"],
        [t(:TR, :scope => :countries), "TR"],
        [t(:UA, :scope => :countries), "UA"],
        [t(:GB, :scope => :countries), "GB"],
        [t(:VA, :scope => :countries), "VA"],
      ]
    end 

    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clinic_params
      params.require(:clinic).permit(:name, :organization, :lat, :lng, :address, :operating_hours, :phone, :cost, :scheduling, :eligibility, :country, :contact_name, :contact_email, :contact_phone, :additional_info, :verified, shifts_attributes: [:id, :day, :opening_time, :closing_time, :clinic_id, :open, :opening_time2, :closing_time2], capabilities_attributes: [:id, :clinic_id, :topic_id, :available])
    end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.haml
.row
  .col-md-12
    .panel.panel-info
      .panel-body
        = form_for @clinic do |f|
          - if @clinic.errors.any?
            #error_explanation
              %h2= "#{pluralize(@clinic.errors.count, "error")} prohibited this clinic from being saved:"
              %ul
                - @clinic.errors.full_messages.each do |msg|
                  %li= msg

          .form-group
            = f.label :name, t('name')
            = f.text_field :name, class: "form-control"
          .form-group
            = f.label :organization, t('organization')
            = f.text_field :organization, class: "form-control"
          .form-group
            = f.label :phone, t('phone_number')
            = f.text_field :phone, class: "form-control"
          .form-group
            = f.label :address, t('address')
            = f.text_area :address, class: "form-control"
          .form-group
            = f.label :lat, t('latitude')
            = f.text_field :lat, class: "form-control"
          .form-group
            = f.label :lng, t('longitude')
            = f.text_field :lng, class: "form-control"
          .form-group
            = f.label :country, t('country')
            %br/
            = f.select :country, options_for_select(@countries), {}, {class: "form-control"}
          .form-group
            = f.label :operating_hours, t('operating_hours')

            = f.fields_for :shifts, @shifts do |s|
              .day
                =s.check_box :open
                %span.day-label
                  =s.label :day, t(s.object.day)

                =s.select :opening_time, options_for_select(@times, s.object.opening_time), {}, {class: "form-control time"}
                =t('to')
                =s.select :closing_time, options_for_select(@times, s.object.closing_time), {}, {class: "form-control time"}

                -if s.object.opening_time2.blank?
                  %a.show-times{:href => "#"} 
                    =t('add_shift')
                    
                  %span.additional
                    =t('and')
                    =s.select :opening_time2, options_for_select(@times, s.object.opening_time2), {include_blank: true}, {class: "form-control time"}
                    =t('to')
                    =s.select :closing_time2, options_for_select(@times, s.object.closing_time2), {include_blank: true}, {class: "form-control time"}

                -else
                  and
                  =s.select :opening_time2, options_for_select(@times, s.object.opening_time2), {include_blank: true}, {class: "form-control time"}
                  =t('to')
                  =s.select :closing_time2, options_for_select(@times, s.object.closing_time2), {include_blank: true}, {class: "form-control time"}

                =s.hidden_field :day, value: s.object.day


          .form-group
            = f.label :services_offered, t('services_offered')

            = f.fields_for :capabilities, @capabilities do |c|
              .day
                =c.check_box :available
                %span.day-label
                  =c.label :day, t(c.object.topic.name)

                =c.hidden_field :clinic_id, value: @clinic.id
                =c.hidden_field :topic_id, value: c.object.topic.id


          .form-group
            = f.label :cost, t('cost')
            = f.select :cost, options_for_select([[t("free"), "free"], [t("charged"), "charged"]]), {}, {class: "form-control"}
          .form-group
            = f.label :scheduling, t('appointment')
            = f.select :scheduling, options_for_select([[t("not_required"), "not_required"], [t("required"), "required"]]), {}, {class: "form-control"}
          .form-group
            = f.label :contact_name, t('clinic_contact_name')
            = f.text_field :contact_name, class: "form-control"
          .form-group
            = f.label :contact_email, t('clinic_contact_email')
            = f.text_field :contact_email, class: "form-control"
          .form-group
            = f.label :contact_phone, t('clinic_contact_phone')
            = f.text_field :contact_phone, class: "form-control"
          .form-group
            = f.label :additional_info, t('additional_info')
            = f.text_area :additional_info, class: "form-control"

          -if current_admin
            .form-group
              =f.check_box :verified
              %span.day-label
                =f.label :verified, "Verified"


          .actions
            = f.submit t('save'), class: "btn btn-success"

:coffeescript
  $('.show-times').click (e) ->
    e.preventDefault()
    $(this).next('.additional').show()
    $(this).hide()

app/views/clinics/_index_map.haml
%script{:src => "https://maps.googleapis.com/maps/api/js?key=#{ENV["google_key"]}&sensor=false&language=#{params[:locale]}", :type => "text/javascript"}


%script
  google.maps.event.addDomListener(window, 'load', init);

  function init() {
  // Basic options for a simple Google Map
  // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
  var mapOptions = {
  // How zoomed in you want the map to start at (always required)
  zoom: 9,

  // The latitude and longitude to center the map (always required)
  -if @lat_lng.present? && @lat_lng.first
    center: new google.maps.LatLng(#{@lat_lng.first}, #{@lat_lng.last}),
  -else
    center: new google.maps.LatLng(#{@clinics_sorted_by_distance.first.first.lat}, #{@clinics_sorted_by_distance.first.first.lng}),

  // Disables the default Google Maps UI components
  disableDefaultUI: true,
  scrollwheel: false,
  draggable: true,
  zoomControl: true,
  scaleControl: true
  }

  // How you would like to style the map. 
  // This is where you would paste any style found on Snazzy Maps.
  

  // Get the HTML DOM element that will contain your map 
  // We are using a div with id="map" seen below in the <body>
  var mapElement = document.getElementById('map');

  // Create the Google Map using out element and options defined above
  var map = new google.maps.Map(mapElement, mapOptions);

  // Custom Map Marker Icon - Customize the map-marker.png file to customize your icon
  -if @lat_lng
    var location_marker = new google.maps.Marker({
    position: new google.maps.LatLng("#{@lat_lng.first}", #{@lat_lng.last}),
    map: map,
    icon: "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"
    });


  -@clinics_sorted_by_distance.each_with_index do |clinic, index|
    var marker#{index} = new google.maps.Marker({
    position: new google.maps.LatLng("#{clinic.first.lat}", #{clinic.first.lng}),
    map: map,
    url: "#{clinic_url(clinic.first)}"
    });

    google.maps.event.addListener(marker#{index}, "click", function () {
    location.assign(marker#{index}.url);
    });

  }

app/views/clinics/_map.haml
%script{:src => "https://maps.googleapis.com/maps/api/js?key=#{ENV["google_key"]}&sensor=false&language=#{params[:locale]}", :type => "text/javascript"}


%script
  google.maps.event.addDomListener(window, 'load', init);

  function init() {
  // Basic options for a simple Google Map
  // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
  var mapOptions = {
  // How zoomed in you want the map to start at (always required)
  zoom: 10,

  // The latitude and longitude to center the map (always required)
  center: new google.maps.LatLng(#{@clinic.lat}, #{@clinic.lng}),

  // Disables the default Google Maps UI components
  disableDefaultUI: true,
  scrollwheel: false,
  draggable: true,
  zoomControl: true,
  scaleControl: true
  }

  // How you would like to style the map. 
  // This is where you would paste any style found on Snazzy Maps.
  

  // Get the HTML DOM element that will contain your map 
  // We are using a div with id="map" seen below in the <body>
  var mapElement = document.getElementById('map');

  // Create the Google Map using out element and options defined above
  var map = new google.maps.Map(mapElement, mapOptions);

  // Custom Map Marker Icon - Customize the map-marker.png file to customize your icon
  -if @lat_lng
    var location_marker = new google.maps.Marker({
    position: new google.maps.LatLng("#{@lat_lng.first}", #{@lat_lng.last}),
    map: map,
    icon: "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"
    });


  var myLatLng = new google.maps.LatLng("#{@clinic.lat}", #{@clinic.lng});
  var marker#{@clinic.id} = new google.maps.Marker({
  position: myLatLng,
  map: map
  });

  }

app/views/clinics/about.haml
.row
  .col-md-12.text-center
    %h1 
      =t('about') 
    %br/
  
  .col-md-12   
    .panel.panel-info
      .panel-body
        %p
          =t('about1') 
  
  .col-md-12   
    .panel.panel-info
      .panel-body
        %p
          =t('about2')
          %a{:href => "#{select_topic_path}", 'data-no-turbolink' => true}
            =t('find_clinic_by_service')
          =t('about3')
  
  .col-md-12   
    .panel.panel-info
      .panel-body
        %p
          =t('about4') 
          %a{:href => "http://www.nhs.uk/conditions/Pages/hub.aspx", target: "_blank"}
            =t('nhs')
          =t('about5')
  
  -unless locale == :ar || locale == :fa
    %br/
    .col-md-12
      %h2
        =t('about6')
        

    .col-md-12   
      .panel.panel-info
        .panel-body
    
          %p
            =t('about7')
             
    
    .col-md-12   
      .panel.panel-info
        .panel-body
          %p
            =t('about8')
            %a{:href => "#{new_clinic_path}"}
              =t('add_clinic')
            =t('about9')
            
    
    .col-md-12   
      .panel.panel-info
        .panel-body
          %p
            =t('about10')
            
    
    %br/
    .col-md-12
      %h2
        =t('who_we_are')
    
    .col-md-12   
      .panel.panel-info
        .panel-body
          %p.center-text
            %a.img{:href => "https://www.doctorsoftheworld.org.uk/", target: "_blank"}
              =image_tag "mdm.png"
              %strong
                =t('dotw')

          %p
            =t('about11')
             
    
    .col-md-12   
      .panel.panel-info
        .panel-body
          %p.center-text
            %a.img{:href => "http://www.reliefwatch.com"}
              =image_tag "danyu.png"
              %strong
                Daniel Yu

          %p
            =t('about12') 
            %a{:href => "http://www.reliefwatch.com"}
              Reliefwatch, 
            =t('about13')
    
    %br/
    .col-md-12   
      %h2=t('about14')

    .col-md-12   
      .panel.panel-info
        .panel-body
          %p.center-text
            For any questions or to find out more please contact Tom McKenzie at
            = mail_to 'tmckenzie@doctorsoftheworld.org.uk', nil, encode: "javascript"
            \.

    .col-md-12   
      .panel.panel-info
        .panel-body
          %p.center-text
            To report any technical issues with the website please contact Daniel Yu at
            = mail_to 'daniel@reliefwatch.com', nil, encode: "javascript"
            \.

app/views/clinics/edit.html.haml
%h1 Edit Clinic

= render 'form'

app/views/clinics/home.haml
.row
  .col-md-12.text-center
    %a.btn.btn-primary.btn-large{:href => "#{clinics_path}", 'data-no-turbolink' => true}
      %h3
        =t('find_clinic')

%br/
%br/
.row
  .col-md-12.text-center
    %a.btn.btn-info.btn-large{:href => "#{select_topic_path}", 'data-no-turbolink' => true}
      %h3
        =t('find_clinic_by_service') 


%br/
%br/
.row
  .col-md-6.col-md-offset-3    
    .panel.panel-info
      .panel-body
        %h4.text-center
          =t('emergency_call_instructions')
          

%br/
%br/
.row
  .col-md-12.text-center
    %h3=t('want_help')
    %br/
    %a.btn.btn-primary{:href => "#{about_path}"}
      %h4
        =t('learn')
    %br/
    %br/
    -unless locale == :ar || locale == :fa

      %a.btn.btn-info{:href => "#{new_clinic_path}"}
        %h4
          =t('add_clinic')
      %br/
      %br/

app/views/clinics/index.html.haml
-if current_admin && @unverified_clinics.present?
  %h2 Unverified Clinics

  %ul.list
    -@unverified_clinics.each do |clinic|
      %li
        %a.list-link{:href => "#{clinic_path(clinic)}", 'data-no-turbolink' => true}
          %span.name
            =clinic.name



%h2
  =t('closest_clinics')
  -if params[:topic]
    =t('for')
    =t(params[:topic])

%br/
.row.filter-topics
  .col-md-12
    %span
      =t('click_to_filter')+':'
    -Topic.all.each do |topic|
      %a.btn.btn-primary{:href => "#{clinics_path}&topic=#{topic.name}", 'data-no-turbolink' => true}
        =t(topic.name)

%br/

-if @current_location
  %h4
    =t('current_location')+':'
    #{@current_location.first}, #{@current_location.last}

%br/




#map
=render 'index_map'

#clinics
  / %input.search{:placeholder => "Search"}/
  
  %ul.list
    -@clinics_sorted_by_distance.each do |clinic|
      %li
        %a.list-link{:href => "#{clinic_path(clinic.first)}", 'data-no-turbolink' => true}
          %span.name
            =clinic.first.name
          %span.distance
            =clinic.last
            =t('km')

.row
  .col-md-12.text-center
    %h3=t('clinics_not_listed')
    %a.btn.btn-info{:href => "#{new_clinic_path}"}
      %h4
        =t('add_clinic')
    %br/
    %br/


:javascript
  var options = {
    valueNames: [ 'name', 'address', 'hours', 'distance' ],
    plugins: [ListPagination({})]
  };

  var userList = new List('clinics', options);

app/views/clinics/new.html.haml
%h1=t('add_clinic')

= render 'form'

app/views/clinics/select_topic.haml
%h2.text-center Select Clinic Service

-@topics.each do |topic|
  %br/
  .row
    .col-md-12.text-center
      %a.btn.btn-primary.btn-large{:href => "#{clinics_path}&topic=#{topic.name}", 'data-no-turbolink' => true}
        %h3
          =t(topic.name)
  %br/

app/views/clinics/show.html.haml
.row
  .col-md-12
    .pull-left
      %h2
        =@clinic.name
        =t('clinic_clarifier')
    .pull-right
      %a.btn.btn-info.btn-large{:href => "#{clinics_path}", 'data-no-turbolink' => true}
        =t('back_to_list')

#map
=render 'map'

.row
  .col-md-12
    .panel.panel-info.dark
      .panel-body
        %p
          %b
            =t('address')+':'
          %br/
          = @clinic.address

        -if @clinic.organization.present?
          %p
            %b=t('organization')+':'
            = @clinic.organization
          %br/

        -if @clinic.contact_phone.present?
          %p
            %b=t('phone_number')+':'
            = @clinic.contact_phone
          %br/

        %p
          %b=t('operating_hours')+':'
          -@shifts.each do |shift|
            %span.shift
              %span.days
                =t(shift.day)
              %span.times
                #{shift.opening_time}-#{shift.closing_time}
                -if shift.opening_time2.present?
                  =t('and')
                  #{shift.opening_time2}-#{shift.closing_time2}
          -if @shifts.empty?
            %p.shift=t('call_clinic_hours')

        %p
          %b=t('services_offered')+':'
          -@capabilities.each do |c|
            %span.shift
              %span.days
                =t(c.topic.name)
        %p
          %b=t('cost')+':'
          =t(@clinic.cost)
        %p
          %b=t('appointment')+':'
          =t(@clinic.scheduling)


-if current_admin
  .row
    .col-md-12.text-center
      %a.btn.btn-primary{:href => "#{edit_clinic_path(@clinic)}"}
        %h3
          =t('edit_clinic')

  %br/
  .row
    .col-md-12.text-center
      %a.btn.btn-primary{:href => "#{clinic_path(@clinic)}", :data => { :confirm => 'Are you sure?', method: :delete }}
        %h3
          Delete Clinic
-else
  .row
    .col-md-6.col-md-offset-3    
      .panel.panel-info
        .panel-body
          %h4.text-center
            =t('incorrect_info')
            %span.gold
              = mail_to 'tmckenzie@doctorsoftheworld.org.uk', nil, encode: "javascript"
            =t('incorrect_info2')