config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :capabilities
  resources :topics
  resources :clinics

  get 'home' => 'clinics#home', as: :home
  get 'about' => 'clinics#about', as: :about
  get 'select_topic' => 'clinics#select_topic', as: :select_topic

  root 'clinics#home'

end

app/models/capability.rb
class Capability < ActiveRecord::Base
  belongs_to :clinic
  belongs_to :topic
end

app/controllers/capabilities_controller.rb
class CapabilitiesController < ApplicationController
  before_action :set_capability, only: [:show, :edit, :update, :destroy]

  # GET /capabilities
  # GET /capabilities.json
  def index
    @capabilities = Capability.all
  end

  # GET /capabilities/1
  # GET /capabilities/1.json
  def show
  end

  # GET /capabilities/new
  def new
    @capability = Capability.new
  end

  # GET /capabilities/1/edit
  def edit
  end

  # POST /capabilities
  # POST /capabilities.json
  def create
    @capability = Capability.new(capability_params)

    respond_to do |format|
      if @capability.save
        format.html { redirect_to @capability, notice: 'Capability was successfully created.' }
        format.json { render :show, status: :created, location: @capability }
      else
        format.html { render :new }
        format.json { render json: @capability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capabilities/1
  # PATCH/PUT /capabilities/1.json
  def update
    respond_to do |format|
      if @capability.update(capability_params)
        format.html { redirect_to @capability, notice: 'Capability was successfully updated.' }
        format.json { render :show, status: :ok, location: @capability }
      else
        format.html { render :edit }
        format.json { render json: @capability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capabilities/1
  # DELETE /capabilities/1.json
  def destroy
    @capability.destroy
    respond_to do |format|
      format.html { redirect_to capabilities_url, notice: 'Capability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capability
      @capability = Capability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capability_params
      params.require(:capability).permit(:topic_id, :clinic_id)
    end
end

app/helpers/capabilities_helper.rb
module CapabilitiesHelper
end

app/views/capabilities/_form.html.haml
= form_for @capability do |f|
  - if @capability.errors.any?
    #error_explanation
      %h2= "#{pluralize(@capability.errors.count, "error")} prohibited this capability from being saved:"
      %ul
        - @capability.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :topic_id
    = f.number_field :topic_id
  .field
    = f.label :clinic_id
    = f.number_field :clinic_id
  .actions
    = f.submit 'Save'

app/views/capabilities/edit.html.haml
%h1 Editing capability

= render 'form'

= link_to 'Show', @capability
\|
= link_to 'Back', capabilities_path

app/views/capabilities/index.html.haml
%h1 Listing capabilities

%table
  %thead
    %tr
      %th Topic
      %th Clinic
      %th
      %th
      %th

  %tbody
    - @capabilities.each do |capability|
      %tr
        %td= capability.topic_id
        %td= capability.clinic_id
        %td= link_to 'Show', capability
        %td= link_to 'Edit', edit_capability_path(capability)
        %td= link_to 'Destroy', capability, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Capability', new_capability_path

app/views/capabilities/new.html.haml
%h1 New capability

= render 'form'

= link_to 'Back', capabilities_path

app/views/capabilities/show.html.haml
%p#notice= notice

%p
  %b Topic:
  = @capability.topic_id
%p
  %b Clinic:
  = @capability.clinic_id

= link_to 'Edit', edit_capability_path(@capability)
\|
= link_to 'Back', capabilities_path