config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :capabilities
  resources :topics
  resources :clinics

  get 'home' => 'clinics#home', as: :home
  get 'about' => 'clinics#about', as: :about
  get 'select_topic' => 'clinics#select_topic', as: :select_topic

  root 'clinics#home'

end

app/views/layouts/application.haml
!!!
%html
  %head
    %title ClinicFinder | Helping Displaced People Find Health Services
    %meta{ :name => "description", :content => "ClinicFinder is a website to help find the nearest health clinic, specifically intended for refugees and displaced people enroute through Europe who require medical services." }
    %meta{ :name => "viewport", :content => "initial-scale=1.0, user-scalable=no" }
    %meta{ :property => "og:title", :content => "ClinicFinder | Helping Displaced People Find Health Services" }
    %meta{ :property => "og:description", :content => "ClinicFinder is a website to help find the nearest health clinic, specifically intended for refugees and displaced people enroute through Europe who require medical services." }
    %meta{ :property => "og:url", :content => "http://www.clinicfinder.org" }
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = favicon_link_tag "fav.png"
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat:400,700", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    -if I18n.locale == :ar || I18n.locale == :fa
      :css
        body {
          text-align: right;
        }

  %body#page-top{"data-spy" => "scroll", "data-target" => ".navbar-fixed-top"}
    / Navigation
    %nav.navbar{:role => "navigation"}
      .container
        .row
          .navbar-header
            %a.navbar-brand.page-scroll{:href => "#{root_path}"}
            .navlink.pull-left
              =link_to "ClinicFinder", root_path
            

            
            .navlink.pull-right.languages
              -if current_admin
                =link_to "Logout", destroy_admin_session_path, :class => 'btn btn-primary logout'
              .btn-group
                %button.btn.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                  %i.fa.fa-language.fa-4x
                %ul.dropdown-menu.dropdown-menu-right
                  -if I18n.locale == :ar
                    %li
                      %a{:href => "?locale=en", 'data-no-turbolink' => true} English
                    %li
                      %a{:href => "?locale=fa", 'data-no-turbolink' => true} فارسی
                  -elsif I18n.locale == :fa
                    %li
                      %a{:href => "?locale=en", 'data-no-turbolink' => true} English
                    %li
                      %a{:href => "?locale=ar", 'data-no-turbolink' => true} العربية
                  -else
                    %li
                      %a{:href => "?locale=ar", 'data-no-turbolink' => true} العربية
                    %li
                      %a{:href => "?locale=fa", 'data-no-turbolink' => true} فارسی


    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert

    
    .container
      = yield
    
    - unless @lat_lng
      :javascript
        getGeoLocation();